# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40f7afc76a7d2f911497848db1a36114a9b36b5119b9f55afc8ba897bb66ebc5958e4801cd9bb44ba3175e056a9cdbd2dddb33807d103f3ddce2c45bd89c569c

test:
  secret_key_base: 169602893975fd5e084280798de2c7c17986e84f5a8b8e7fd1fd004dc7b77881c920b3d7c2dc25467937694c2b704d09e1c6128f14476ceb513a821898a771bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
